### ISSUE TITLE
Blueprint css

### ISSUE THREAD

**Issue by serkandurusoy** [mvpspace/redux-starter-kit#4]
I don't like the fact that we are including the css manually. Can't we get it from npm? Meteor's build tool certainly supports importing css from within npm packages!

**Comment by ecerroni** [comment]
You're right. It should work out of the box, but it hadn't.

It works with React + Blueprint. 

When I put Meteor in the picture it isn't behaving as expected so I made this workaround.

I'll investigate further though and post results here.

**Comment by ecerroni** [comment]
Done
